name: build & publish

on: [push]

jobs:
  build-linux:
    name: Build & publish (linux)
    runs-on: [self-hosted, linux]
    env:
      DOTNET_INSTALL_DIR: "./.dotnet"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup dotnet 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Build
        run: dotnet build
      - name: Publish
        run: dotnet publish -o bin/Publish/linux
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: game-linux
          path: bin/Publish/linux/

  build-windows:
    name: Build & publish (windows)
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: dotnet build
      - name: Publish
        run: dotnet publish -o bin/Publish/windows
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: game-windows
          path: bin/Publish/windows/

