name: builds

on: [push]

jobs:
  build-linux:
    name: Build (linux 64-bit)
    runs-on: [self-hosted, linux]
    env:
      DOTNET_INSTALL_DIR: "./.dotnet"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup dotnet 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Build
        run: dotnet build

  build-windows:
    name: Build (windows 64-bit)
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: dotnet build
